-- Create table
create table t_attemp_CARD
(
  objectid                     INTEGER not null,
  gt_version                   INTEGER default 0,
  card_kind                    INTEGER,
  is_permit_sys_del            INTEGER default 0 not null,
  service_state                INTEGER default 1 not null,
  use_type                     INTEGER default 1 not null,
  native_name                  VARCHAR2(255),
  version                      VARCHAR2(255),
  fdn                          VARCHAR2(255),
  card_id                      VARCHAR2(255),
  protect_type                 VARCHAR2(255),
  equipmentcode                VARCHAR2(64),
  protect_card                 VARCHAR2(255),
  model                        VARCHAR2(255),
  is_protect                   VARCHAR2(20),
  object_type_code             INTEGER default 5000 not null,
  hard_version                 VARCHAR2(255),
  is_replace                   INTEGER default 0,
  ports_num                    INTEGER,
  userlabel                    VARCHAR2(255),
  put_into_used                DATE,
  photoelectricity             INTEGER default 1 not null,
  property                     INTEGER default 1,
  setup_time                   DATE,
  related_device_cuid          VARCHAR2(255),
  related_upper_component_cuid VARCHAR2(255),
  ownership                    INTEGER default 1 not null,
  length                       FLOAT,
  preserver                    VARCHAR2(255),
  vendor                       VARCHAR2(255),
  label_cn                     VARCHAR2(200) not null,
  component_name               VARCHAR2(255),
  height                       FLOAT,
  related_project_cuid         VARCHAR2(172),
  serial                       VARCHAR2(255),
  width                        FLOAT,
  remark                       VARCHAR2(255),
  cuid                         VARCHAR2(172) not null,
  isdelete                     INTEGER,
  create_time                  DATE,
  last_modify_time             DATE,
  project_state                INTEGER,
  live_cycle                   INTEGER default 1 not null,
  use_state                    INTEGER default 1 not null,
  related_usetask_cuid         VARCHAR2(255),
  livemodify_time              DATE,
  livemodify_user              VARCHAR2(255),
  standard_name                VARCHAR2(255),
  dev_type                     NUMBER(19),
  card_sub_kind                VARCHAR2(20),
  use_vendor                   NUMBER(19) default 1 not null
);
-- Create/Recreate primary, unique and foreign key constraints 
alter table t_attemp_CARD
  add primary key (OBJECTID)
  using index ;
  
  
  -- Create table
create table t_his_CARD
(
  objectid                     INTEGER not null,
  gt_version                   INTEGER default 0,
  card_kind                    INTEGER,
  is_permit_sys_del            INTEGER default 0 not null,
  service_state                INTEGER default 1 not null,
  use_type                     INTEGER default 1 not null,
  native_name                  VARCHAR2(255),
  version                      VARCHAR2(255),
  fdn                          VARCHAR2(255),
  card_id                      VARCHAR2(255),
  protect_type                 VARCHAR2(255),
  equipmentcode                VARCHAR2(64),
  protect_card                 VARCHAR2(255),
  model                        VARCHAR2(255),
  is_protect                   VARCHAR2(20),
  object_type_code             INTEGER default 5000 not null,
  hard_version                 VARCHAR2(255),
  is_replace                   INTEGER default 0,
  ports_num                    INTEGER,
  userlabel                    VARCHAR2(255),
  put_into_used                DATE,
  photoelectricity             INTEGER default 1 not null,
  property                     INTEGER default 1,
  setup_time                   DATE,
  related_device_cuid          VARCHAR2(255),
  related_upper_component_cuid VARCHAR2(255),
  ownership                    INTEGER default 1 not null,
  length                       FLOAT,
  preserver                    VARCHAR2(255),
  vendor                       VARCHAR2(255),
  label_cn                     VARCHAR2(200) not null,
  component_name               VARCHAR2(255),
  height                       FLOAT,
  related_project_cuid         VARCHAR2(172),
  serial                       VARCHAR2(255),
  width                        FLOAT,
  remark                       VARCHAR2(255),
  cuid                         VARCHAR2(172) not null,
  isdelete                     INTEGER,
  create_time                  DATE,
  last_modify_time             DATE,
  project_state                INTEGER,
  live_cycle                   INTEGER default 1 not null,
  use_state                    INTEGER default 1 not null,
  related_usetask_cuid         VARCHAR2(255),
  livemodify_time              DATE,
  livemodify_user              VARCHAR2(255),
  standard_name                VARCHAR2(255),
  dev_type                     NUMBER(19),
  card_sub_kind                VARCHAR2(20),
  use_vendor                   NUMBER(19) default 1 not null
);
-- Create/Recreate primary, unique and foreign key constraints 
alter table t_his_CARD
  add primary key (OBJECTID)
  using index ;

