-- Create table
create table t_attemp_PTP
(
  idn                   VARCHAR2(255),
  objectid              NUMBER(19),
  create_time           DATE,
  last_modify_time      DATE,
  gt_version            NUMBER(19),
  isdelete              NUMBER(19),
  mstp_nanfcmode        NUMBER(19),
  mstp_pvid             VARCHAR2(255),
  is_permit_sys_del     NUMBER(19),
  mstp_port_type        NUMBER(19),
  mstp_flowctrl         NUMBER(19),
  mstp_anfcmode         NUMBER(19),
  mstp_lcas_flag        NUMBER(19),
  mstp_encapprotocol    NUMBER(19),
  mstp_pptenable        NUMBER(19),
  is_share              NUMBER(19),
  mstp_edetect          NUMBER(19),
  mstp_tag_flag         NUMBER(19),
  loop_info             VARCHAR2(255),
  mstp_encapformat      NUMBER(19),
  port_type             NUMBER(19),
  mstp_cflen            NUMBER(19),
  sys_no                VARCHAR2(255),
  mstp_bmsgsuppress     NUMBER(19),
  interface_type        NUMBER(19),
  currentwavenum        NUMBER(19),
  mstp_fcscalseq        NUMBER(19),
  native_name           VARCHAR2(255),
  related_vb_cuid       VARCHAR2(255),
  loop_state            NUMBER(19),
  mstp_vlanpriority     NUMBER(19),
  mstp_portenable       NUMBER(19),
  mstp_userid           NUMBER(19),
  domain                NUMBER(19),
  mstp_vlanid           NUMBER(19),
  mstp_workmode         NUMBER(19),
  mstp_port_servicetype NUMBER(19),
  mstp_scrambel         NUMBER(19),
  line_branch_type      NUMBER(19),
  waverate              NUMBER(19),
  object_type_code      NUMBER(19),
  mstp_extendeader      NUMBER(19),
  related_card_cuid     VARCHAR2(255),
  mstp_maxpacketlen     NUMBER(19),
  project_state         NUMBER(19),
  wave_path_no          VARCHAR2(255),
  frequency             VARCHAR2(255),
  live_cycle            NUMBER(19),
  use_state             NUMBER(19),
  related_usetask_cuid  VARCHAR2(255),
  livemodify_time       DATE,
  livemodify_user       VARCHAR2(255),
  receive_frequency     VARCHAR2(20),
  send_frequency        VARCHAR2(20),
  port_loop_stat        NUMBER(19),
  standard_name         VARCHAR2(255),
  layer_info            VARCHAR2(500),
  vlan                  VARCHAR2(30),
  dev_type              NUMBER(19),
  port_sub_type         NUMBER(19),
  admin_state           NUMBER(19),
  operating_state       NUMBER(19),
  available_bandwidth   VARCHAR2(20),
  port_no               NUMBER(19),
  is_conn_state         NUMBER(19),
  port_rate             NUMBER(19),
  port_state            NUMBER(19),
  remark                VARCHAR2(2000),
  fdn                   VARCHAR2(255),
  is_channel            NUMBER(1),
  related_ne_cuid       VARCHAR2(255),
  userlabel             VARCHAR2(255),
  related_ems_cuid      VARCHAR2(255),
  termination_mode      NUMBER(19),
  directionality        NUMBER(19),
  label_cn              VARCHAR2(200),
  related_district_cuid VARCHAR2(255),
  cuid                  VARCHAR2(172),
  dev_ip                VARCHAR2(16),
  mac_tag_flag          NUMBER(19)
);
-- Create/Recreate indexes 
create index attemp_PTP_02 on t_attemp_PTP (RELATED_NE_CUID, PORT_SUB_TYPE);
create index attemp_PTP_05 on t_attemp_PTP (RELATED_NE_CUID, PORT_STATE, PORT_SUB_TYPE);
create index attemp_PTP_CARD on t_attemp_PTP (RELATED_CARD_CUID);
create index attemp_PTP_CUID_INDEX on t_attemp_PTP (CUID);
create index attemp_PTP_EMS on t_attemp_PTP (RELATED_EMS_CUID);
create index attemp_PTP_FDN on t_attemp_PTP (FDN);
create index attemp_PTP_LABEL on t_attemp_PTP (LABEL_CN);
create index attemp_PTP_NE on t_attemp_PTP (RELATED_NE_CUID);


-- Create table
create table t_his_PTP
(
  idn                   VARCHAR2(255),
  objectid              NUMBER(19),
  create_time           DATE,
  last_modify_time      DATE,
  gt_version            NUMBER(19),
  isdelete              NUMBER(19),
  mstp_nanfcmode        NUMBER(19),
  mstp_pvid             VARCHAR2(255),
  is_permit_sys_del     NUMBER(19),
  mstp_port_type        NUMBER(19),
  mstp_flowctrl         NUMBER(19),
  mstp_anfcmode         NUMBER(19),
  mstp_lcas_flag        NUMBER(19),
  mstp_encapprotocol    NUMBER(19),
  mstp_pptenable        NUMBER(19),
  is_share              NUMBER(19),
  mstp_edetect          NUMBER(19),
  mstp_tag_flag         NUMBER(19),
  loop_info             VARCHAR2(255),
  mstp_encapformat      NUMBER(19),
  port_type             NUMBER(19),
  mstp_cflen            NUMBER(19),
  sys_no                VARCHAR2(255),
  mstp_bmsgsuppress     NUMBER(19),
  interface_type        NUMBER(19),
  currentwavenum        NUMBER(19),
  mstp_fcscalseq        NUMBER(19),
  native_name           VARCHAR2(255),
  related_vb_cuid       VARCHAR2(255),
  loop_state            NUMBER(19),
  mstp_vlanpriority     NUMBER(19),
  mstp_portenable       NUMBER(19),
  mstp_userid           NUMBER(19),
  domain                NUMBER(19),
  mstp_vlanid           NUMBER(19),
  mstp_workmode         NUMBER(19),
  mstp_port_servicetype NUMBER(19),
  mstp_scrambel         NUMBER(19),
  line_branch_type      NUMBER(19),
  waverate              NUMBER(19),
  object_type_code      NUMBER(19),
  mstp_extendeader      NUMBER(19),
  related_card_cuid     VARCHAR2(255),
  mstp_maxpacketlen     NUMBER(19),
  project_state         NUMBER(19),
  wave_path_no          VARCHAR2(255),
  frequency             VARCHAR2(255),
  live_cycle            NUMBER(19),
  use_state             NUMBER(19),
  related_usetask_cuid  VARCHAR2(255),
  livemodify_time       DATE,
  livemodify_user       VARCHAR2(255),
  receive_frequency     VARCHAR2(20),
  send_frequency        VARCHAR2(20),
  port_loop_stat        NUMBER(19),
  standard_name         VARCHAR2(255),
  layer_info            VARCHAR2(500),
  vlan                  VARCHAR2(30),
  dev_type              NUMBER(19),
  port_sub_type         NUMBER(19),
  admin_state           NUMBER(19),
  operating_state       NUMBER(19),
  available_bandwidth   VARCHAR2(20),
  port_no               NUMBER(19),
  is_conn_state         NUMBER(19),
  port_rate             NUMBER(19),
  port_state            NUMBER(19),
  remark                VARCHAR2(2000),
  fdn                   VARCHAR2(255),
  is_channel            NUMBER(1),
  related_ne_cuid       VARCHAR2(255),
  userlabel             VARCHAR2(255),
  related_ems_cuid      VARCHAR2(255),
  termination_mode      NUMBER(19),
  directionality        NUMBER(19),
  label_cn              VARCHAR2(200),
  related_district_cuid VARCHAR2(255),
  cuid                  VARCHAR2(172),
  dev_ip                VARCHAR2(16),
  mac_tag_flag          NUMBER(19)
);
-- Create/Recreate indexes 
create index his_PTP_02 on t_his_PTP (RELATED_NE_CUID, PORT_SUB_TYPE);
create index his_PTP_05 on t_his_PTP (RELATED_NE_CUID, PORT_STATE, PORT_SUB_TYPE);
create index his_PTP_CARD on t_his_PTP (RELATED_CARD_CUID);
create index his_PTP_CUID_INDEX on t_his_PTP (CUID);
create index his_PTP_EMS on t_his_PTP (RELATED_EMS_CUID);
create index his_PTP_FDN on t_his_PTP (FDN);
create index his_PTP_LABEL on t_his_PTP (LABEL_CN);
create index his_PTP_NE on t_his_PTP (RELATED_NE_CUID);
